version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bankbranch
      - POSTGRES_USER=carlos.morais
      - POSTGRES_PASSWORD=123456789
      - MAX_CONNECTIONS=300
